add tests

diff --git a/.github/workflows/mingw.yml b/.github/workflows/mingw.yml
--- a/.github/workflows/mingw.yml
+++ b/.github/workflows/mingw.yml
@@ -23,16 +23,30 @@ jobs:
         repository: sass/sassc
         path: sassc
 
+    - name: Install Ruby dependencies
+      run: gem install minitest hrx --no-document
+
+    - name: make
+      run: mingw32-make -j4 sassc
+
+    # TODO: checkout specific PR ref if needed
     - name: Checkout sass-spec
       uses: actions/checkout@v2
       with:
         repository: sass/sass-spec
         path: sass-spec
 
-    - name: Install Ruby dependencies
-      run: gem install minitest hrx --no-document
-    - name: make
-      run: mingw32-make -j4 sassc
+    - name: Run sass-spec tests
+      run: ruby sass-spec/sass-spec.rb --probe-todo --impl libsass -c $env:TargetPath -s sass-spec/spec
 
-    - name: Verify build version
-      run: ${{ env.TargetPath }} -v
+    # See comments in gh-1774 for details.
+    - name: Explicitly testing the case when cwd has Unicode characters
+      run: |
+        cd test/e2e/unicode-pwd/Sáss-UŢF8/
+        &$env:TargetPath ./input.scss 2>&1>$null
+        if(-not($?)) {
+          echo "Failed!"
+          exit 1
+        } else {
+          echo "Success!"
+        }
